export const GET_SHIPMENT_CARRIERS_REQUEST = "GET_SHIPMENT_CARRIERS_REQUEST";
export const GET_SHIPMENT_CARRIERS_SUCCESS = "GET_SHIPMENT_CARRIERS_SUCCESS";
export const GET_SHIPMENT_CARRIERS_FAIL = "GET_SHIPMENT_CARRIERS_FAIL";

export const SET_SELECTED_CARRIER_REQUEST = "SET_SELECTED_CARRIER_REQUEST";
